### ISSUE TITLE
Colors don't work with Tailwind JIT

### ISSUE THREAD

**Issue by antfu** [antfu/vite-windi-tailwind-jit-compare#1]
Did I misconfigure something? Would need some help, thanks!

**Comment by userquin** [comment]
it seems the class `.text-cyan-500` is missing, instead using `fill='currentcolor'` add  `fill-current` to the svg class.
I have it working with `text-indigo-500`:
```html
<svg class="flex-shrink-0 h-5 w-5 text-cyan-500" viewBox="0 0 20 20" fill="currentColor">
```
use this:
```html
<svg class="flex-shrink-0 h-5 w-5 fill-current text-indigo-500" viewBox="0 0 20 20">
```

**Comment by antfu** [comment]
Because the `cyan` is not enabled in the colors? I don't think it's expected for jit tho, they should work out-of-box 🤔

**Comment by userquin** [comment]
`blue` is also missing...

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/111491280-04029e00-873c-11eb-8deb-4bd8d35e6227.png)

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/111491499-34e2d300-873c-11eb-814f-0d83e0beb3c9.png)

**Comment by userquin** [comment]
`light-blue` to be exact...

**Comment by edimitchel** [comment]
You miss to add the tailwind configuration:

tailwind.config.js
```js
const colors = require('tailwindcss/colors')

module.exports = {
  purge: [
    '../*.vue',
  ],
  theme: {
    extend: {
      colors: {
        'light-blue': colors.lightBlue,
        cyan: colors.cyan,
      },
    },
  },
  variants: {},
  plugins: [],
}
```

**Comment by cubecleveland** [comment]
i notice gree-200 is alos missing.... am i wrong....
